pipeline {
    agent any

    tools {
        maven 'Maven-3.9.11'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Clonando el repositorio desde la rama dev...'
                git url: 'https://github.com/Alexlms123/ecommerce-microservice-backend-app.git', branch: 'dev'
            }
        }

        stage('Build & Test') {
            steps {
                dir('favourite-service') {
                    echo 'Construyendo y probando el favourite-service con Maven...'
                    sh 'mvn clean package'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('favourite-service') {
                    script {
                        echo "Construyendo la imagen de Docker para el favourite-service..."
                        def imageName = "alexlms123/favourite-service:latest"
                        sh "docker build -t ${imageName} ."
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                dir('favourite-service') {
                    script {
                        echo "Subiendo la imagen a Docker Hub..."
                        def imageName = "alexlms123/favourite-service:latest"
                        withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                            sh "echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin"
                            sh "docker push ${imageName}"
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finalizado.'
            cleanWs()
        }
    }
}
