pipeline {
    
    agent any

    tools {
        maven 'Maven-3.9.11'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Clonando el repositorio desde la rama dev...'
                git url: 'https://github.com/Alexlms123/ecommerce-microservice-backend-app.git', branch: 'dev'
            }
        }

        stage('Build & Test') {
            steps {
                
                dir('user-service') {
                    echo 'Construyendo y probando el user-service con Maven...'
                    sh 'mvn clean package'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('user-service') {
                    script {
                        echo "Construyendo la imagen de Docker para el user-service..."
                        def imageName = "alexlms123/user-service:latest"
                        
                        sh "docker build -t ${imageName} ."
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                dir('user-service') {
                    script {
                        echo "Subiendo la imagen a Docker Hub..."
                        def imageName = "alexlms123/user-service:latest"

                        // Usa las credenciales guardadas en Jenkins para hacer login en Docker Hub.
                        // El ID 'dockerhub-credentials' debe coincidir con el que creaste.
                        withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                            // Hacemos login de forma segura, pasando la contraseña por la entrada estándar.
                            sh "echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin"
                            
                            // Subimos la imagen.
                            sh "docker push ${imageName}"
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finalizado.'
        
            cleanWs()
        }
    }
}