pipeline {
    
    agent any

    tools {
        maven 'Maven-3.9.11'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Clonando el repositorio desde la rama dev...'
                git url: 'https://github.com/Alexlms123/ecommerce-microservice-backend-app.git', branch: 'dev'
            }
        }

        stage('Build & Test') {
            steps {
                
                dir('user-service') {
                    echo 'Construyendo y probando el user-service con Maven...'
                    sh 'mvn clean package'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('user-service') {
                    echo "Construyendo la imagen de Docker para el user-service..."
                
                    def imageName = "alexlms123/user-service:latest"
                    
                    sh "docker build -t ${imageName} ."
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline finalizado.'
        
            cleanWs()
        }
    }
}